/**
 * Every visitor-facing string. Albanian first (the audience is in Tirana), English second.
 * Rules: short sentences, concrete verbs, one label per intent, no invented facts.
 * Prices, stock and delivery fees never live here: they come from the admin.
 * No em or en dashes anywhere (DESIGN.md).
 */
export type Lang = 'sq' | 'en';
export const LANGS: readonly Lang[] = ['sq', 'en'];
export const isLang = (v: unknown): v is Lang => v === 'sq' || v === 'en';

const sq = {
  lang: 'sq' as Lang,
  langName: 'Shqip',
  switchTo: 'English',
  switchShort: 'EN',
  meta: {
    homeTitle: 'Dresses by Greta, fustane mbrëmjeje në Tiranë',
    homeDescription: 'Fustane mbrëmjeje, mature dhe koktej nga dyqani në Tiranë. Zgjidh masën, porosite online dhe paguaj në dorëzim.',
    shopTitle: 'Shop, Dresses by Greta',
    shopDescription: 'Të gjitha fustanet e Dresses by Greta me çmimin dhe masat në gjendje. Porosit online dhe paguaj në dorëzim.',
    sizeTitle: (size: string) => `Fustane në masën ${size}, Dresses by Greta`,
    checkoutTitle: 'Porosia, Dresses by Greta',
    notFoundTitle: 'Faqja nuk u gjet, Dresses by Greta',
  },
  a11y: {
    skip: 'Kalo te përmbajtja',
    wordmark: 'Dresses by Greta, kryefaqja',
    sizeIndex: 'Masat',
    spreads: 'Fustanet',
    gallery: 'Fotot e fustanit',
    close: 'Mbyll',
    qtyDown: 'Një më pak',
    qtyUp: 'Një më shumë',
    zoom: 'Shiko foton të plotë',
    photoOf: (n: number, total: number) => `Foto ${n} nga ${total}`,
    prev: 'Foto e mëparshme',
    next: 'Foto tjetër',
    removeFilter: 'Hiq filtrin',
  },
  demo: 'Të dhëna demo: çmimet dhe gjendja janë shembuj për testim, jo të dyqanit.',
  nav: {
    menu: 'Menu',
    close: 'Mbyll',
    search: 'Kërko',
    bag: 'Çanta',
    region: 'Gjuha',
    shop: 'Dyqani',
    lookbook: 'Shop',
    all: 'Të gjitha fustanet',
    bySize: 'Sipas masës',
    visit: 'Dyqani në Tiranë',
    instagram: 'Instagram',
  },
  hero: {
    wordmark: 'Dresses by Greta',
    cta: 'Shiko fustanet',
    alt: 'Fustan i gjatë me pajeta blu safir, në plazh nën diell',
  },
  categories: { all: 'Të gjitha', gowns: 'Të gjata', mini: 'Mini & midi', black: 'Të zeza', tv: 'Në TV' },
  sizes: {
    title: 'Sipas masës',
    all: 'Të gjitha',
    count: (n: number) => (n === 1 ? '1 fustan' : `${n} fustane`),
    none: 'Asnjë tani',
    guide: 'Masat janë europiane: 34 është XS, 36 S, 38 M, 40 L, 42 XL.',
    label: (size: string, letter: string) => `Masa ${size} (${letter})`,
  },
  home: {
    openLookbook: 'Shiko fustanet',
  },
  shop: {
    title: 'Shop',
    contents: 'Indeksi',
    spreads: 'Faqet',
    count: (n: number) => (n === 1 ? '1 fustan' : `${n} fustane`),
    inSize: (n: number, size: string) => (n === 1 ? `1 fustan në masën ${size}` : `${n} fustane në masën ${size}`),
    empty: (size: string) => `Asnjë fustan në masën ${size} tani. Provo një masë tjetër ose pyet në Instagram.`,
    emptyAll: 'Fustanet e reja po fotografohen. Ndërkohë i gjen në Instagram.',
    open: 'Shiko fustanin',
    soldOut: 'E shitur',
  },
  product: {
    size: 'Masa',
    chooseSize: 'Zgjidh masën',
    add: 'Shto në çantë',
    added: 'U shtua në çantë',
    soldOut: 'E shitur',
    sizeSoldOut: (size: string) => `Masa ${size} është shitur`,
    lastOne: 'E fundit në këtë masë',
    description: 'Përshkrimi',
    delivery: 'Dërgesa dhe pagesa',
    deliveryBody: 'Paguan në dorëzim, kur e merr porosinë. Tarifa e transportit shfaqet te porosia.',
    instagram: 'Shiko në Instagram',
    ask: 'Pyet në Instagram',
    next: 'Fustani tjetër',
    back: 'Kthehu te fustanet',
    noPrice: 'Çmimi në Instagram',
    was: 'Më parë',
    rent: 'Për qira, pyet në Instagram',
  },
  bag: {
    title: 'Çanta',
    empty: 'Çanta jote është bosh.',
    emptyBody: 'Zgjidh një fustan në Shop dhe porosite këtu.',
    browse: 'Shiko fustanet',
    remove: 'Hiq',
    qty: 'Sasia',
    size: 'Masa',
    subtotal: 'Nëntotali',
    checkout: 'Vazhdo te porosia',
    unavailable: 'Nuk është më në gjendje',
    onlyLeft: (n: number) => (n === 1 ? 'Ka vetëm 1' : `Ka vetëm ${n}`),
    note: 'Transporti llogaritet te porosia. Paguan në dorëzim.',
  },
  checkout: {
    title: 'Porosia',
    contact: 'Të dhënat e tua',
    name: 'Emri dhe mbiemri',
    phone: 'Numri i telefonit',
    phoneHint: 'Të telefonojmë në këtë numër për ta konfirmuar porosinë.',
    email: 'Email (jo i detyrueshëm)',
    delivery: 'Dërgesa',
    zone: 'Zona',
    zones: { tirana: 'Tiranë', albania: 'Qytet tjetër në Shqipëri', kosovo: 'Kosovë' },
    city: 'Qyteti',
    address: 'Adresa',
    addressHint: 'Rruga, pallati, kati, apartamenti',
    notes: 'Shënime për dërgesën (jo të detyrueshme)',
    payment: 'Pagesa',
    cod: 'Pagesë në dorëzim',
    codBody: 'Paguan me para në dorë kur të vjen porosia.',
    card: 'Me kartë',
    cardBody: 'Paguan online me kartë debiti ose krediti.',
    summary: 'Përmbledhja',
    subtotal: 'Nëntotali',
    shipping: 'Transporti',
    shippingTbc: 'Konfirmohet me telefon',
    shippingFree: 'Falas',
    total: 'Totali',
    place: 'Dërgo porosinë',
    placing: 'Po dërgohet',
    emptyTitle: 'Çanta është bosh.',
    required: 'Plotëso këtë fushë.',
    phoneInvalid: 'Shkruaj një numër telefoni të vlefshëm, për shembull 069 123 4567.',
    emailInvalid: 'Shkruaj një adresë email të vlefshme, ose lëre bosh.',
    soldOut: (name: string, size: string) => `${name}, masa ${size}, nuk është më në gjendje. Hiqe nga çanta për të vazhduar.`,
    failed: 'Porosia nuk u dërgua. Provo përsëri pas pak.',
    consent: 'Duke dërguar porosinë pranon që dyqani të të telefonojë për ta konfirmuar.',
    edit: 'Ndrysho çantën',
  },
  confirmation: {
    title: (n: number) => `Porosia nr. ${n}`,
    thanks: 'Faleminderit. Porosia jote u regjistrua.',
    next: 'Dyqani do të të telefonojë për ta konfirmuar porosinë dhe për të caktuar dërgesën.',
    paid: 'Pagesa me kartë u krye.',
    unpaid: 'Paguan në dorëzim.',
    awaiting: 'Pagesa me kartë nuk është kryer ende.',
    retry: 'Paguaj me kartë',
    cancelled: 'Kjo porosi u anulua.',
    items: 'Fustanet',
    deliverTo: 'Adresa e dërgesës',
    continue: 'Vazhdo blerjet',
  },
  search: {
    title: 'Kërko',
    placeholder: 'Kërko fustane ose ngjyra',
    results: (n: number) => (n === 1 ? '1 fustan' : `${n} fustane`),
    none: 'Asnjë fustan me këtë emër. Provo një ngjyrë: e kuqe, blu, e zezë.',
    clear: 'Fshi',
  },
  visit: {
    title: 'Dyqani në Tiranë.',
    address: 'Rruga Andon Zako Çajupi, pas LSI, Tiranë',
    maps: 'Hap në Google Maps',
    body: "Eja t'i provosh në dyqan. Fustanet e reja dalin çdo javë në Instagram.",
    ask: 'Pyet në Instagram',
  },
  footer: {
    shop: 'Dyqani',
    help: 'Ndihmë',
    dresses: 'Fustanet',
    follow: 'Ndiq @dressesbygreta',
    followers: '26,2 mijë ndjekës',
    privacy: 'Kjo faqe nuk përdor cookies për reklama. Çanta ruhet vetëm në këtë pajisje.',
    rules: 'Rregullat e qirasë',
  },
  popup: {
    lead: 'Mos humb asgjë.',
    body: 'Fustanet e reja dalin çdo javë në Instagram.',
    cta: 'Ndiq në Instagram',
    close: 'Mbyll',
  },
  pay: {
    title: 'Pagesa me kartë (test)',
    body: 'Kjo faqe imiton bankën vetëm në kompjuterin e zhvillimit. Asnjë kartë nuk tarifohet.',
    pay: 'Paguaj (test)',
    fail: 'Refuzo pagesën (test)',
  },
  notFound: {
    title: 'Kjo faqe nuk ekziston.',
    body: 'Ndoshta ky fustan nuk është më në shitje. Të tjerët janë këtu.',
    cta: 'Shiko fustanet',
  },
};

export type Copy = typeof sq;

const en: Copy = {
  lang: 'en',
  langName: 'English',
  switchTo: 'Shqip',
  switchShort: 'SQ',
  meta: {
    homeTitle: 'Dresses by Greta, evening dresses in Tirana',
    homeDescription: 'Evening, prom and cocktail dresses from the boutique in Tirana. Pick your size, order online and pay on delivery.',
    shopTitle: 'Shop, Dresses by Greta',
    shopDescription: 'Every Dresses by Greta dress with its price and the sizes in stock. Order online and pay on delivery.',
    sizeTitle: (size: string) => `Dresses in size ${size}, Dresses by Greta`,
    checkoutTitle: 'Checkout, Dresses by Greta',
    notFoundTitle: 'Page not found, Dresses by Greta',
  },
  a11y: {
    skip: 'Skip to content',
    wordmark: 'Dresses by Greta, home',
    sizeIndex: 'Sizes',
    spreads: 'The dresses',
    gallery: 'Photos of the dress',
    close: 'Close',
    qtyDown: 'One fewer',
    qtyUp: 'One more',
    zoom: 'View the full photo',
    photoOf: (n: number, total: number) => `Photo ${n} of ${total}`,
    prev: 'Previous photo',
    next: 'Next photo',
    removeFilter: 'Remove filter',
  },
  demo: "Demo data: prices and stock are examples for testing, not the shop's.",
  nav: {
    menu: 'Menu',
    close: 'Close',
    search: 'Search',
    bag: 'Bag',
    region: 'Language',
    shop: 'Shop',
    lookbook: 'Shop',
    all: 'All dresses',
    bySize: 'By size',
    visit: 'The shop in Tirana',
    instagram: 'Instagram',
  },
  hero: {
    wordmark: 'Dresses by Greta',
    cta: 'See the dresses',
    alt: 'Long sapphire sequin gown on a sunlit beach',
  },
  categories: { all: 'All', gowns: 'Gowns', mini: 'Mini & midi', black: 'Black', tv: 'Seen on TV' },
  sizes: {
    title: 'By size',
    all: 'All',
    count: (n: number) => (n === 1 ? '1 dress' : `${n} dresses`),
    none: 'None right now',
    guide: 'Sizes are European: 34 is XS, 36 S, 38 M, 40 L, 42 XL.',
    label: (size: string, letter: string) => `Size ${size} (${letter})`,
  },
  home: {
    openLookbook: 'See the dresses',
  },
  shop: {
    title: 'Shop',
    contents: 'Index',
    spreads: 'Pages',
    count: (n: number) => (n === 1 ? '1 dress' : `${n} dresses`),
    inSize: (n: number, size: string) => (n === 1 ? `1 dress in size ${size}` : `${n} dresses in size ${size}`),
    empty: (size: string) => `No dress in size ${size} right now. Try another size or ask on Instagram.`,
    emptyAll: 'New dresses are being photographed. Meanwhile they are on Instagram.',
    open: 'See the dress',
    soldOut: 'Sold out',
  },
  product: {
    size: 'Size',
    chooseSize: 'Choose your size',
    add: 'Add to bag',
    added: 'Added to bag',
    soldOut: 'Sold out',
    sizeSoldOut: (size: string) => `Size ${size} is sold out`,
    lastOne: 'Last one in this size',
    description: 'Description',
    delivery: 'Delivery and payment',
    deliveryBody: 'Pay on delivery, when the order reaches you. The delivery fee shows at checkout.',
    instagram: 'View on Instagram',
    ask: 'Ask on Instagram',
    next: 'Next dress',
    back: 'Back to the dresses',
    noPrice: 'Price on Instagram',
    was: 'Was',
    rent: 'To rent it, ask on Instagram',
  },
  bag: {
    title: 'Bag',
    empty: 'Your bag is empty.',
    emptyBody: 'Choose a dress in the Shop and order it here.',
    browse: 'See the dresses',
    remove: 'Remove',
    qty: 'Quantity',
    size: 'Size',
    subtotal: 'Subtotal',
    checkout: 'Go to checkout',
    unavailable: 'No longer in stock',
    onlyLeft: (n: number) => (n === 1 ? 'Only 1 left' : `Only ${n} left`),
    note: 'Delivery is added at checkout. Pay on delivery.',
  },
  checkout: {
    title: 'Checkout',
    contact: 'Your details',
    name: 'Full name',
    phone: 'Phone number',
    phoneHint: 'We call this number to confirm the order.',
    email: 'Email (optional)',
    delivery: 'Delivery',
    zone: 'Area',
    zones: { tirana: 'Tirana', albania: 'Another city in Albania', kosovo: 'Kosovo' },
    city: 'City',
    address: 'Address',
    addressHint: 'Street, building, floor, flat',
    notes: 'Delivery notes (optional)',
    payment: 'Payment',
    cod: 'Pay on delivery',
    codBody: 'Pay in cash when the order arrives.',
    card: 'By card',
    cardBody: 'Pay online with a debit or credit card.',
    summary: 'Summary',
    subtotal: 'Subtotal',
    shipping: 'Delivery',
    shippingTbc: 'Confirmed by phone',
    shippingFree: 'Free',
    total: 'Total',
    place: 'Place order',
    placing: 'Sending',
    emptyTitle: 'Your bag is empty.',
    required: 'Fill in this field.',
    phoneInvalid: 'Enter a valid phone number, for example 069 123 4567.',
    emailInvalid: 'Enter a valid email address, or leave it empty.',
    soldOut: (name: string, size: string) => `${name}, size ${size}, is no longer in stock. Remove it from the bag to continue.`,
    failed: 'The order was not sent. Try again in a moment.',
    consent: 'By placing the order you agree that the shop may call you to confirm it.',
    edit: 'Edit the bag',
  },
  confirmation: {
    title: (n: number) => `Order no. ${n}`,
    thanks: 'Thank you. Your order is in.',
    next: 'The shop will call you to confirm the order and arrange delivery.',
    paid: 'Card payment received.',
    unpaid: 'Pay on delivery.',
    awaiting: 'The card payment has not gone through yet.',
    retry: 'Pay by card',
    cancelled: 'This order was cancelled.',
    items: 'Dresses',
    deliverTo: 'Delivery address',
    continue: 'Continue shopping',
  },
  search: {
    title: 'Search',
    placeholder: 'Search dresses or colours',
    results: (n: number) => (n === 1 ? '1 dress' : `${n} dresses`),
    none: 'No dress by that name. Try a colour: red, blue, black.',
    clear: 'Clear',
  },
  visit: {
    title: 'The shop in Tirana.',
    address: 'Rruga Andon Zako Çajupi, pas LSI, Tiranë',
    maps: 'Open in Google Maps',
    body: 'Come and try them on in the shop. New dresses appear every week on Instagram.',
    ask: 'Ask on Instagram',
  },
  footer: {
    shop: 'The shop',
    help: 'Help',
    dresses: 'Dresses',
    follow: 'Follow @dressesbygreta',
    followers: '26.2K followers',
    privacy: 'This site uses no advertising cookies. Your bag is kept only on this device.',
    rules: 'Rental rules',
  },
  popup: {
    lead: 'Stay in the know.',
    body: 'New dresses appear every week on Instagram.',
    cta: 'Follow on Instagram',
    close: 'Close',
  },
  pay: {
    title: 'Card payment (test)',
    body: 'This page stands in for the bank on the development machine only. No card is charged.',
    pay: 'Pay (test)',
    fail: 'Decline the payment (test)',
  },
  notFound: {
    title: 'This page does not exist.',
    body: 'This dress may no longer be on sale. The others are here.',
    cta: 'See the dresses',
  },
};

export const copy: Record<Lang, Copy> = { sq, en };

/** Internal link that keeps the visitor's language (Albanian needs no parameter). */
export function href(path: string, lang: Lang, params: Record<string, string | undefined> = {}): string {
  const q = new URLSearchParams();
  for (const [k, v] of Object.entries(params)) if (v) q.set(k, v);
  if (lang === 'en') q.set('lang', 'en');
  const s = q.toString();
  return s ? `${path}?${s}` : path;
}
